### ISSUE TITLE
The exec doesn't fail the build after it failed

### ISSUE THREAD

**Issue by dmatej** [eclipse-ee4j/glassfish-build-maven-plugin#97]
The stacktrace was caused by my local changes in GlassFish, but the build failed much later in tests. It should fail immediately.

```
[INFO] --- glassfishbuild:3.2.27:exec (create-domain) @ web ---
[INFO] executable: /media/data-samsung/data/dmatej/work/repo/git/glassfish/appserver/distributions/web/target/stage/glassfish7/bin/asadmin
[INFO] commandLineArgs: --user admin create-domain --template=/media/data-samsung/data/dmatej/work/repo/git/glassfish/appserver/distributions/web/target/stage/glassfish7/glassfish/common/templates/gf/appserver-domain.jar --nopassword --savelogin=true --checkports=false --adminport 4848 --instanceport 8080 --keytooloptions CN=localhost domain1
[INFO] [exec] Exception in thread "main" java.lang.ExceptionInInitializerError
[INFO] [exec]   at com.sun.enterprise.admin.servermgmt.cli.CreateDomainCommand.createTheDomain(CreateDomainCommand.java:406)
[INFO] [exec]   at com.sun.enterprise.admin.servermgmt.cli.CreateDomainCommand.executeCommand(CreateDomainCommand.java:268)
[INFO] [exec]   at com.sun.enterprise.admin.cli.CLICommand.execute(CLICommand.java:291)
[INFO] [exec]   at com.sun.enterprise.admin.cli.AdminMain.executeCommand(AdminMain.java:323)
[INFO] [exec]   at com.sun.enterprise.admin.cli.AdminMain.doMain(AdminMain.java:260)
[INFO] [exec]   at org.glassfish.admin.cli.AsadminMain.main(AsadminMain.java:33)
[INFO] [exec] Caused by: java.time.format.DateTimeParseException: Text '2023-02-26T13:18:25UTC' could not be parsed at index 19
[INFO] [exec]   at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
[INFO] [exec]   at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948)
[INFO] [exec]   at java.base/java.time.Instant.parse(Instant.java:395)
[INFO] [exec]   at com.sun.appserv.server.util.Version.<clinit>(Version.java:94)
[INFO] [exec]   ... 6 more
[INFO] [exec] Result: 1
```

**Comment by pzygielo** [comment]
Interesting.
Plugin's default in `:exec` is
```java
    @Parameter(property = "failOnError", defaultValue = "true")
    private Boolean failOnError;
```

and the GF's config in `appserver/distributions/web/pom.xml` doesn't alter that.

I'd expect [ExecTask](https://ant.apache.org/manual-1.9.x/api/index.html?org/apache/tools/ant/taskdefs/ExecTask.html) to throw `BuildException` in such case (result != 0), but your log doesn't seem to have that.
Is maven handling only `MojoException`s and happily accepting `RuntimeException`s? Can't belive that.

As you assigned this - perhaps you already know the place to be modified. I'll be happy to learn that.

**Comment by pzygielo** [comment]
03ea112 - while 3.2.27-RELEASE does not include that
```
* 03ea112 Plugin returns failure status if an error occurs
| * 062ba93 (tag: 3.2.27-RELEASE) Prepare release org.glassfish.build:glassfishbuild-maven-plugin:3.2.27
|/  
* 89cd552 (tag: initial-contribution) Initial contribution
```

Upgrade plugin to 3.2.28 in GF.

**Comment by pzygielo** [comment]
Ekhm - 3.2.28-RELEASE apparently also has no 03ea112500087a0be5ffe9ee5608d54feeb067fe

**Comment by dmatej** [comment]
So, when do we plan the next release? I have found yet one fix I did for the Payara clone missing here ...
